version: '3.7'

#networks:
#  back-tier:

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  app:
    container_name: onlinemed-backend-docker
    image: 'onlinemed-backend-docker:latest'
    build:
      context: ./onlinemed-backend
      dockerfile: ./Dockerfile
    depends_on:
      - postgresDB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDB:5432/onlinemed_db
      - SPRING_DATASOURCE_USERNAME=onlinemed_root
      - SPRING_DATASOURCE_PASSWORD=e976908e-fab7-11ea-9418-5f9b5705bac5
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - "8080:8080"
    restart: always
    deploy:
        mode: global

  postgresDB:
    image: 'postgres:13-alpine'
    container_name: postgresDB
    environment:
      - POSTGRES_USER=onlinemed_root
      - POSTGRES_PASSWORD=e976908e-fab7-11ea-9418-5f9b5705bac5
      - POSTGRES_DB=onlinemed_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5555"
    expose:
      - "5555" # protect locally installed postgres port

  prometheus:
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    volumes:
      - ./:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    links:
      - app:app
    depends_on:
      - app
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "0"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

    env_file:
      - ./grafana/config.monitoring
    restart: always
